spring:
  application:
    name: ricardo
  datasource:
    url: jdbc:postgresql://postgres:5432/ricardo
    username: ricardo
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
  mvc:
    problemdetails:
      enabled: on
