spring:
  application:
    name: ricardo
  datasource:
    url: jdbc:postgresql://localhost:5432/ricardo
    username: ricash
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
  mvc:
    problemdetails:
      enabled: on
