apiVersion: v1
kind: Service
metadata:
  name: ricardo
  labels:
    app: ricardo
spec:
  selector:
    app: ricardo
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer